export const artistsItems = [
  { name: "Arpita Modak", img: "artist1.png" },
  { name: "Arpita Modak", img: "artist2.png" },
  { name: "Arpita Modak", img: "artist3.png" },
  { name: "Subhamay Karjee", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist5.png" },
  { name: "Arpita Modak", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist5.png" },
  { name: "Arpita Modak", img: "artist6.png" },
  { name: "Arpita Modak", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist8.png" },
];
export const homeCardContent = [
  { name: "QC Approval", value: "12546" },
  { name: "To Live", value: "24" },
  { name: "In Review", value: "56" },
];
export const releaseItems = [
  {
    name: "Buker Bhitor DJ Baje",
    type: "Error",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },

  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
];

export const Release_Claim = [
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "REJECTED",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
];
export const LablesItems = [
  {
    name: "T series",
    type: "Reject",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Zee Music Co.",
    type: "Reject",
    img: "Zee-Music.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "Saregama.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Vevo",
    type: "Approved",
    img: "Vevo.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Steam Music",
    type: "Approved",
    img: "Steam-Music.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Steam Music India",
    type: "Reject",
    img: "Steam-Music-India.png",
    date: "Sep 21, 2024",
  },
  {
    name: "T series",
    type: "Reject",
    img: "T-series.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Zee Music Co.",
    type: "Reject",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
];
export const support = [
  {
    id: "#236265926502",
    title: "Incorrect Song Title Listed on Streaming Platforms",
    date: "22 Jan 2025, 11am",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 11am",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 11am",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 11am",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 11am",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025, 7pm",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
];
export const transactions = [
  {
    type: "Withdrawn",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "Reject",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Withdrawn",
    method: "PayPal",
    methoda_sample: "********@gmail.com",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Withdrawn",
    method: "PayPal",
    methoda_sample: "********@gmail.com",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "Reject",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Withdrawn",
    method: "bKash",
    methoda_sample: "***** ***72",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Withdrawn",
    method: "bKash",
    methoda_sample: "***** ***72",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
];
export const singleReleaseATrackData = [
  {
    DSPs: "Spotify",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "SloundCloud",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Amazon Prime",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Amazon Music Unlimited",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Deezer",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
];
export const singleReleaseARevenueData = [
  {
    Total: "Total",
    Revenue: "$16,251",
  },
];
export const releaseAlbumInfo = [
  { title: "Release Tittle:", value: "Ami dur hote tomarei dekhechi" },
  { title: "Primary Artists:", value: "Ayuska Bhowmik, Arpita Modak" },
  { title: "Featuring:", value: "Subhamay Karjee" },
  { title: "Genre:", value: "Indian" },
  { title: "Subgenre:", value: "Bengali Indian" },
  { title: "Label name:", value: "Dream records" },
  { title: "Release date:", value: "23 Jan 2025" },
  { title: "Version/Subtittle:", value: "Bengali, English" },
  { title: "Format:", value: "Single" },
  { title: "℗ line:", value: "00012345678" },
  { title: "© line:", value: "87654321000" },
  { title: "Production Year:", value: "2025" },
  { title: "UPC/EAN:", value: "840405732119" },
  { title: "Producer Catalog Number:", value: "340405732119" },
];
export const releaseTrackDetails = [
  { title: "Track type:", value: "Cover " },
  { title: "Genre:", value: "Indian" },
  { title: "Tittle:", value: "Tere bin" },
  { title: "Sub-genre", value: "Indian Hindi" },
  { title: "Version/Subtittle:", value: "Hindi" },
  { title: "Parental Advisory:", value: "No" },
  { title: "℗ line:", value: "2025 DreamWave Music Group" },
  { title: "Track Tittle Language:", value: "Hindi" },
  { title: "Production Year:", value: "2025" },
  { title: "Lyrics Language:", value: "Hindi" },
  { title: "Publisher:", value: "Auska Bhowmik" },
  {
    title: "Lyrics:",
    value:
      "Tere Bin Main Yun Kaise JiyaKaise Jiya Tere BinTere Bin Main Yun Kaise JiyaKaise Jiya Tere BinLekar Yaad Teri Raaten Meri KatiLekar Yaad Teri Raaten Meri Kati",
  },
  { title: "ISRC Code:", value: "4395734073935" },
];
export const artistSocialItems = {
  socialLinks: [
    {
      name: "Spotify",
      img: "spotify-icon.png",
      url: "",
      placeholder: "eg. 6kXwOyEW4VffTqJut6h7J6",
    },
    {
      name: "Apple Music",
      img: "apple-music.png",
      url: "",
      placeholder: "eg. 123456789",
    },
    {
      name: "Facebook Page",
      img: "facebook.png",
      url: "",
      placeholder: "eg. facebook.com/username",
    },
    {
      name: "Instagram Profile",
      img: "instagram.png",
      url: "",
      placeholder: "eg. username",
    },
    {
      name: "Youtube Channel",
      img: "youtube-icon.png",
      url: "",
      placeholder: "eg. youtube.com/username",
    },
  ],
};
export const labelSocialItems = [
  {
    name: "Facebook Page",
    img: "facebook.png",
    url: "",
    placeholder: "eg. facebook.com/username",
  },
  {
    name: "Instagram Profile",
    img: "instagram.png",
    url: "",
    placeholder: "eg. username",
  },
  {
    name: "Youtube Channel",
    img: "youtube-icon.png",
    url: "",
    placeholder: "eg. youtube.com/username",
  },
];
export const albumTrackList = [
  {
    title: "Ami Dur Hote Tomarei Dekhechi",
    artist: "Ayuska Bhowmik",
    duration: "04:23",
    content: ["Lyrics line 1", "Lyrics line 2"],
  },
  {
    title: "Tumi Amar",
    artist: "Arijit Singh",
    duration: "03:45",
    content: ["Verse 1", "Verse 2", "Verse 3"],
  },
];
export const chartData = [
  { month: "Jan", value: 12 },
  { month: "Feb", value: 25 },
  { month: "Mar", value: 50 },
  { month: "Apr", value: 40 },
  { month: "May", value: 52 },
  { month: "Jun", value: 25 },
  { month: "Jul", value: 15 },
  { month: "Aug", value: 33 },
  { month: "Sep", value: 40 },
  { month: "Oct", value: 25 },
  { month: "Nov", value: 35 },
  { month: "Dec", value: 10 },
];
export const releaseCredits = [
  {
    title: "Primary Artist:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Lyricist:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Featuring:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Composer:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Arranger:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
    },
  },
  {
    title: "Producer:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
    },
  },
];
export const completeArtistData = {
  image:
    "https://ih1.redbubble.net/image.467902823.2780/fpp,small,lustre,wall_texture,product,750x1000.u5.jpg",
  officialName: "me",
  socialLinks: [
    {
      name: "Spotify",
      img: "spotify-icon.png",
      url: "ksjdhf",
      placeholder: "eg. 6kXwOyEW4VffTqJut6h7J6",
    },
    {
      name: "Apple Music",
      img: "apple-music.png",
      url: "lksh",
      placeholder: "eg. 123456789",
    },
    {
      name: "Facebook Page",
      img: "facebook.png",
      url: "",
      placeholder: "eg. facebook.com/username",
    },
    {
      name: "Instagram Profile",
      img: "instagram.png",
      url: "",
      placeholder: "eg. username",
    },
    {
      name: "Youtube Channel",
      img: "youtube-icon.png",
      url: "sdf",
      placeholder: "eg. youtube.com/username",
    },
  ],
};
